### ISSUE TITLE
intermittent frame drops

### ISSUE THREAD

**Issue by hooke007** [tsl0922/ImPlay#28] opened 2023-02-11 17:43 UTC
**Describe the bug**
Intermittent frame-drops would happen when rendering OSD.

**To Reproduce**
1. Run mpv and load any file.
2. Toggle stat.

**Expected behavior**
No frame drops.

**Screenshots**
<img src="https://user-images.githubusercontent.com/41094733/218272860-0f3e82f7-738b-445d-b55a-1c10e44202d4.jpg" width=400>

**Environment (please complete the following information):**
 - OS: [Windows 10 Pro]
 - Version [22H2]

**Additional context**
N/A

**Comment by tsl0922** [comment] 2023-02-12 15:46
It's caused by mpv property querying on render.

I've fixed an issue related to it, but it should also can be reproduced when context menu is opened.

**Comment by tsl0922** [comment] 2023-02-13 10:04
Most of the mpv properties used for gui display are cached now, closing.

**Closed by tsl0922** 2023-02-13 10:04 UTC
Labels: bug
