### ISSUE TITLE
Pure Black  for white top bar

### ISSUE THREAD

**Issue by trimechee** [tsl0922/ImPlay#71] opened 2023-11-16 23:17 UTC
Hello, dark mode allows us to reduce blue light which can tire our eyes at night, save battery power...I like the pure full black mode theme which looks like the high contrast theme, so we would like please for more visual comfort a pure black theme color even in the white top bar, thank you !

**Comment by tsl0922** [comment] 2023-11-17 06:19
Duplicate of #10

**Closed by tsl0922** 2023-11-17 06:19 UTC
Labels: enhancement

**Comment by trimechee** [comment] 2023-11-17 09:35
Hello @tsl0922 , th
